language: r
cache: packages
sudo: false

script:
  - Rscript -e "blogdown::build_site()"

after_success:
  - cp -r public/* publish/.

deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GITHUB_OAUTH_TOKEN
  keep-history: true
  local-dir: publish
  on: 
    branch: master


